### ISSUE TITLE
Add SNI support

### ISSUE THREAD

**Issue by hharsunen** [RayBa82/DVBViewerController#20]
If Apache reverse proxy server has "SSLStrictSNIVHostCheck on" the client connection fails even on Android lollipop. Never Android versions automatically support SNI on SSL/TLS connection, the code doesn't seem to be compatible with these newer SSL/TLS implementations. It doesn't help to update libs/httpclientandroidlib-1.2.1.jar which holds this fix (https://issues.apache.org/jira/browse/HTTPCLIENT-1119). So perhaps some code fixing should be done to fix the issue.

**Comment by hharsunen** [comment]
http://blog.dev001.net/post/67082904181/android-using-sni-and-tlsv1-2-with-apache might help

**Comment by RayBa82** [comment]
Probably fixed by switching to "okhttp" https://github.com/square/okhttp from square https://github.com/square/okhttp/issues/830

**Comment by hharsunen** [comment]
Verified working, now client connections work even if recording service reverse proxy has "SSLStrictSNIVHostCheck on" set. Thanks.
