### ISSUE TITLE
Adding more video resolution

### ISSUE THREAD

**Issue by thaischumi** [RayBa82/DVBViewerController#22]
Dear developers,

Could you add some more video streaming resolution to DVBViewer Controller on Android?

At the moment we have:
Max. Width: 1280, 1024, 800, 720, 640,480, 320,240,180
and Max. Height: 720, 640, 576, 480, 360, 280, 240, 200, 160

Could you add 1920, 960, 854,512 to Max. Width
and 1080, 540,288 (or change 280 to 288) to and Max. Height,
so we will able to choose resolution like: Full HD 1920x1080, qHD 960x540, FWVGA 854x480...

Thanks very much,

Best regards.

**Comment by RayBa82** [comment]
All video presets are downloaded from RS in ffmpegprefs.ini, so this is configurable by user now -> closed
