### ISSUE TITLE
Add Lead/Follow-up times to Timers and Program Recordings

### ISSUE THREAD

**Issue by dpankov** [RayBa82/DVBViewerController#69]
There is one discrepancy compared to DVBViewer itself or DVBRecService's web interface. The problem is that the creation of record timers (both when directly selecting the "Record" option for an item in the Channel EPG or when selecting the "Create Timer" option again from Channel EPG) doesn't use the configured "Lead" and "Follow-up" times from the recording service. I see that they are accessible from the Rec Service status window but unlike the web interface of the Rec Service the timer programing in DVBViewer Controller simply ignores them.
I think DVBViewer Controller should use them in the following way:
  - for direct recordings these two should be automatically calculated and applied to the newly created timer
  - in the "Create Timer" and "Timer Details" UI windows the "lead" and "Follow-up" timer settings should have their own edit boxes/fields next to (above/bellow) the Start/Stop ones and they should be initially filled in with the defaults from the Rec Service configuration.

**Comment by RayBa82** [comment]
fixed in next release

**Comment by carlu93** [comment]
I'm really looking forward to this feature. I saw you implementing it already. Is it possible to get a beta APK or something like that? I would like to test this important feature.

**Comment by hharsunen** [comment]
I think easiest method is to opt in for beta in Google Play store https://play.google.com/store/apps/details?id=org.dvbviewer.controller

**Comment by dpankov** [comment]
Sadly it's not even available as beta

**Comment by hharsunen** [comment]
Then do this https://code.google.com/archive/p/dvbviewer-controller/wikis/beta.wiki

**Comment by hharsunen** [comment]
or try that, I think I'm beta tester because of that. At least I don't remember doing anything else. Maybe @RayBa82 could add the current info to wiki? 
edit: actually there's already https://github.com/RayBa82/DVBViewerController/wiki/How-to-become-a-Beta-tester

**Comment by RayBa82** [comment]
Just uploaded a new Beta in Google Play.
Some new features might not be complete, but hey you asked for it ;-)

**Comment by RayBa82** [comment]
App has been removed from Google Play, because of "unauthorized use of copyrighted content".
This is just ridiculous and i complained... 
I will get an answer within 72 hours from Google.
