### ISSUE TITLE
Recorded files not deleted

### ISSUE THREAD

**Issue by vovvenr** [RayBa82/DVBViewerController#93]
Recorded files are no longer deleted with the use of DVBViewerController. This did work in previous versions.
When deleting a recording through DVBViewerController the entry in the recording list in DVBViewer Media Server is deleted, but the the file(s) remain on the disk.
DVB Media Server version 2.1.5.2
DVBViewerController version 1.5.0 build 9

Regards,

**Comment by vovvenr** [comment]
Tested with DVBViewerController version 1.4.2 and deleting a record works again.
Definitely a bug in 1.5.0

Regards,

**Comment by RayBa82** [comment]
Requires the DVBViewer Media Server, does not work with the old Recording Service anymore.
Recording Service is not fully supported anymore -> No issue -> close

**Comment by vovvenr** [comment]
I clearly state in the problem description that this problem appears with DVBViewer Media Server version 2.1.5.2 which is the latest release.

I do not mention Recording Service anywhere in my problem statement.

Please reopen this issue as you have closed it with the wrong assumption.

 

Regards,

                             Vovven
